extends RefCounted
## Module used by the CSG_2D nodes to perform boolean union operations on polygons. (A + B)
class_name Bool2D_Union

## Applies the boolean union operation on the provided polygons.
static func apply_operation( toPolys : Array[ Dictionary ], boolPolys : Array[ Dictionary ] ) -> Array[ Dictionary ]:
	var operatingPolys : Array[ Dictionary ] = toPolys.duplicate_deep()
	var operatingBoolPolys : Array[ Dictionary ] = boolPolys.duplicate_deep()
	var finalPolys : Array[ Dictionary ] = []

	# Loop through all the toPolys and try to combine them with any of the boolPolys.
	for polyIndex in range(operatingPolys.size()):
		# The "operatingBoolPolys" array is modified by the _combine_polys() function later in the loop, 
		# so we check if it's empty after every loop in case all the boolean polygons have been combined 
		# already.
		if operatingBoolPolys.is_empty():
			break
		
		var poly = operatingPolys[polyIndex]
		var combineResult = _combine_polys( poly, operatingBoolPolys )
		# if the combineResult comes back non-empty then we know the combination was successful and we replace 
		# the current polygon with the combined result. 
		if combineResult.size() > 0:
			operatingPolys[polyIndex] = combineResult
			
	# Next, after some of the toPolys have been combined with the boolPolys, we loop through all the toPolys 
	# again and merge any that now overlap.
	while operatingPolys.size() > 0:
		var poly : Dictionary = operatingPolys.pop_front()
		var combineResult = _combine_polys( poly, operatingPolys )
		if combineResult.size() > 0:
			operatingPolys.append( combineResult )
		else:
			finalPolys.append( poly )

	return finalPolys + operatingBoolPolys


## Attempts to combine the poly with any polygon in polyBs, removing the first successfully combined polygon from 
## polyBs and returning the combined result. If no combination was successful, returns an empty dictionary.
static func _combine_polys( poly : Dictionary, polyBs : Array[ Dictionary ] ) -> Dictionary:
	var polyA : Dictionary = poly.duplicate()
	var unionSucess := false
	var polyBindex := 0
	
	while polyBs.size() > polyBindex:
		var polyB : Dictionary = polyBs[ polyBindex ].duplicate()

		# First we check if the two polygons intersect at all, if not we move on.
		var intersectionResults : Array = Geometry2D.intersect_polygons( polyA.body, polyB.body )
		if not intersectionResults.is_empty():

			# We check if the polyB is actually just an "island" inside one of the holes of polyA and if so we 
			# skip the combination process and move on.
			var boolIsIsland : bool = false
			for hole in polyA.holes:
				var holeClipRes : Array = Geometry2D.clip_polygons( polyB.body, hole )
				if holeClipRes.is_empty():
					boolIsIsland = true
					break
			
			if boolIsIsland:
				polyBindex += 1
				continue
			
			# If the boolean polygon isn't an island inside one of the holes, we mark the union a success and
			# remove the polyB from the polyB array.
			else:
				unionSucess = true
				polyBs.remove_at( polyBindex )
			
			var survivingHoles : Array = []
			var holeIndex := 0
			# We loop through each hole in polyA and clip it against polyB, adding any clip results to the 
			# surviving holes array and then we do the same for each hole in polyB against polyA. After that we 
			# also check if any of the holes in polyA and polyB overlap, adding said overlaps to the surviving holes as well.
			for holeA in polyA.holes:
				var clipRes : Array = Geometry2D.clip_polygons( holeA, polyB.body )

				for res in clipRes:
					res.reverse()
					survivingHoles.append( res )

			for holeB in polyB.holes:
				var clipRes : Array = Geometry2D.clip_polygons( holeB, polyA.body )
				if not clipRes.is_empty():
					for res in clipRes:
						res.reverse()
						survivingHoles.append( res )

				for holeA : PackedVector2Array in polyA.holes:
					var holeIntersectRes : Array = Geometry2D.intersect_polygons( holeB, holeA )

					for res in holeIntersectRes:
						res.reverse()
						survivingHoles.append( res )

			# Finally after all the hole logic we perform the union operation the bodies of polyA and polyB, applying
			# the result to polyA's body and appending any new holes generated by the union to polyA's holes along with
			# the surviving holes.
			var unionRes : Array = Geometry2D.merge_polygons( polyA.body, polyB.body )
			polyA.body = unionRes.pop_front()
			polyA.holes.clear()
			for res in unionRes:
				polyA.holes.append( res )
			
			for hole in survivingHoles:
				polyA.holes.append( hole )
		else:
			polyBindex += 1

	if unionSucess:
		return polyA
	else:
		return {}